---

# Folder Creation For Backups
- name: Prepare Folder For Backups
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Folder
      file:
        path: "{{ backup_location }}"
        state: directory
      run_once: yes


# Cisco Devices
- name: Backup Devices Iformation For Devices
  hosts: Cisco
  gather_facts: false
  tasks:
    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: Run Commands On Network Device
      cisco.ios.ios_command: 
        commands:
          - show bootvar
          - show version
          - show inventory
          - show running-config
      register: cisco_backup_config

    - name: Store Config To Directory
      copy:
        content:  | 
          {{ cisco_backup_config.stdout[0] }}
          {{ cisco_backup_config.stdout[1] }}
          {{ cisco_backup_config.stdout[2] }}
          {{ cisco_backup_config.stdout[3] }}
        dest: "{{ backup_location }}/{{ inventory_hostname }}.{{ timestamp.stdout }}.txt"
 
# Dell Devices
- name: Device Backup For Dell
  hosts: Dell
  tasks:
    - name: Run Commands On Network Device
      dellemc.os10.os10_command:
        commands:
          - show boot
          - show version
          - show license status
          - show interface transceiver
          - show inventory
          - show running-configuration
        register: dell_backup_config

    - name: Store Dell Config To Directory
      copy:
        content:  | 
          {{ dell_backup_config.stdout[0] }}
          {{ dell_backup_config.stdout[1] }}
          {{ dell_backup_config.stdout[2] }}
          {{ dell_backup_config.stdout[3] }}
          {{ dell_backup_config.stdout[4] }}
          {{ dell_backup_config.stdout[5] }}
        dest: "{{ backup_location }}/{{ inventory_hostname }}.{{ timestamp.stdout }}.txt"


# F5 
- name: Run Show Commands On Big IP F5
  hosts: F5
  connection: ansible.netcommon.network_cli
  tasks:
    - name: CLI F5 Show Commands
      f5networks.f5_modules.bigip_command:
        commands:
          - show sys hardware
          - list net interface all-properties
          - list net interface media-active vendor serial
        register: f5_backup_config

    - name: Store Config To Directory
      copy:
        content:  | 
          {{ f5_backup_config.stdout[0] }}
          {{ f5_backup_config.stdout[1] }}
          {{ f5_backup_config.stdout[2] }}
        dest: "{{ backup_location }}/{{ inventory_hostname }}.{{ timestamp.stdout }}.txt"


# PowerVault
- name: Run Show Commands On PowerVault
  hosts: PowerVault
  connection: ansible.netcommon.network_cli
  gather_facts: false 
  tasks:
    - name: CLI PowerVault Show Commands
      dellemc.openmanage.idrac_system_info:
        ome_device_info:
          hostname: "<IP-ADDRESS>"
          username: "emergency"
          password: "password"
          fact_subset: "basic_inventory"
          system_query_options:
        register: powervault_backup

    - name: Store Config To Directory
      copy:
        content: "{{ powervault_backup.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"


  # NetApp
- name: Run Commands On NetApp
  hosts: NetApp
  connection: ansible.netcommon.network_cli
  gather_facts: false
  tasks:
    - name: CLI Show Command
      netapp.ontap.na_ontap_command:
        hostname: "{{ hostname }}"
        username: "{{ admin username }}"
        password: "{{ admin password }}"
        command: ['system show -instance', 'system license show-serial-numbers']
        return_dict: true
        commands:
      register: NetApp_backup

    - name: Store NetApp Config To Directory
      copy:
        content: "{{ NetApp_backup.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"

            











...