---
# Folder Creation
- name: Prepare Folder For Backups
  hosts: localhost
  gather_facts: false

  vars:
    backup_location: ./Documents/Device_Backup

  tasks:
    - name: Create Folder
      file:
        path: "{{ backup_location }}"
        state: directory
      run_once: yes
# Cisco Devices
- name: Backup Devices Iformation For Devices
  hosts: Cisco
  tasks:
    - name: Run Commands On Network Device
      ios_command:
        commands:
          - show boot
          - show version
          - show license
          - show inventory
          - show hw-module all entity
          - show running-configuration
      register: cisco_backup_config

    - name: Store Config To Directory
      copy:
        src: "{{ cisco_backup_config.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"
 

# Dell Devices
- name: Device Backup For Dell
  hosts: Dell
  tasks:
    - name: Run Commands On Network Device
      dellemc.os10.os10_command:
        commands:
          - show boot
          - show version
          - show license status
          - show interface transceiver
          - show inventory
          - show running-configuration
        register: dell_backup_config

    - name: Store Config To Directory
      copy:
        src: "{{ dell_backup_config.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"
# F5 
- name: Run Show Commands On Big IP F5
  hosts: F5
  connection: ansible.netcommon.network_cli
  tasks:
    - name: CLI F5 Show Commands
      f5networks.f5_modules.bigip_command:
        commands:
          - show sys hardware
          - list net interface all-properties
          - list net interface media-active vendor serial
        register: f5_backup_config

    - name: Store Config To Directory
      copy:
        src: "{{ f5_backup_config.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"
# PowerVault
- name: Run Show Commands On PowerVault
  hosts: PowerVault
  connection: ansible.netcommon.network_cli
  gather_facts: false 
  tasks:
    - name: CLI PowerVault Show Commands
      dellemc.openmanage.idrac_system_info:
        ome_device_info:
          hostname: "<IP-ADDRESS>"
          username: "emergency"
          password: "password"
          fact_subset: "basic_inventory"
          system_query_options:
        register: powervault_backup

    - name: Store Config To Directory
      copy:
        src: "{{ powervault_backup.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"
  # NetApp
- name: Run Commands On NetApp
  hosts: NetApp
  connection: ansible.netcommon.network_cli
  gather_facts: false
  tasks:
    - name: CLI Show Command
      netapp.ontap.na_ontap_command:
        hostname: "{{ hostname }}"
        username: "{{ admin username }}"
        password: "{{ admin password }}"
        command: ['system show -instance', 'system license show-serial-numbers']
        return_dict: true
        commands:
      register: NetApp_backup

    - name: Store NetApp Config To Directory
      copy:
        src: "{{ NetApp_backup.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"

            











...