---

- name: Backup Devices Iformation For Devices
  hosts: Cisco
  connection: 
  gather_facts: false

  vars:
    backup_location: ./Documents/Device_Backup

  tasks:
    - name: Create Folder
      file:
        path: "{{ backup_location }}"
        state: directory
      run_once: yes

    - name: Run Commands On Network Device
      cisco.ios.ios_command:
        commands:
          - show boot
          - show version
          - show license
          - show inventory
          - show hw-module all entity
          - show running-configuration
        register: cisco_backup_config

    - name: Store Config To Directory
      copy:
        src: "{{ cisco_backup_config.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"

- name: Device Backup For Dell
  hosts: Dell
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Run Commands On Network Device
      ios_command:
        commands:
          - show boot
          - show version
          - show license status
          - show interface transceiver
          - show inventory
          - show running-configuration
        register: dell_backup_config

    - name: Store Config To Directory
      copy:
        src: "{{ dell_backup_config.stdout[0] }}"
        dest: "{{ backup_location }}/{{ inventory_hostname }}.txt"

- name: Run Show Commands On Big IP F5
  hosts: F5
  connection: network_cli
  gather_facts: false 

  tasks:
    - name: Run Commands On Big IP F5
      
